[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-L/opt/homebrew/opt/libiconv/lib"]

[target.x86_64-apple-darwin]
linker = "clang"  
rustflags = ["-C", "link-arg=-L/opt/homebrew/opt/libiconv/lib"]
